webui/config/routes.rb
Examui::Application.routes.draw do

  resources :examen
  resources :listados
  resources :opcions
  resources :pregunta
  resources :asignaturas

  devise_for :users

  get 'nueva_pregunta/:id' => 'pregunta#nueva_pregunta', :as => :nueva_pregunta
  get 'nueva_opcion/:id' => 'opcions#nueva_opcion', :as => :nueva_opcion
  get 'nuevo_examen/:id' => 'examen#new', :as => :nuevo_examen
  get 'clave/:id' => 'examen#clave', :as => :clave
  get 'generate/latex/master/:id' => 'latex#latex_master', :as => :latex_master

  post 'update_clave' => 'examen#update_clave', :as => :update_clave

  root 'asignaturas#index'
end

webui/app/controllers/examen_controller.rb
class ExamenController < ApplicationController
  before_action :set_examan, only: [:show, :edit, :update, :destroy]

  def clave
    @examan = Examan.find(params[:id])
  end

  def show
  end

  def new
    @asignatura = Asignatura.find(params[:id])
    @examan = Examan.new
    @examan.asignatura_id = @asignatura.id
  end

  def edit
    @asignatura = @examan.asignatura
  end

  def get_etiquetas
    list = []
    for etiq in @examan.asignatura.listado_de_etiquetas
      list << etiq if params["etiqueta_#{etiq}"]
    end
    list.join(',')
  end

  def get_preguntas
    list = []
    for etiqueta in @examan.listado_de_etiquetas
      for pregunta in Preguntum.from_etiqueta(etiqueta)
        list << pregunta if params["pregunta_#{pregunta.id}"] && !list.include?(pregunta)
      end
    end
    list
  end

  def get_cantidades
    list = []
    for etiqueta in @examan.listado_de_etiquetas
      list << "#{etiqueta}:#{params["cantidad_#{etiqueta}"]}" if params["cantidad_#{etiqueta}"]
    end
    list.join('|')
  end

  def create
    @examan = Examan.new(examan_params)
    @examan.etiquetas = get_etiquetas

    respond_to do |format|
      if @examan.save
        format.html { redirect_to edit_examan_path(@examan), notice: 'Examan was successfully created.' }
        format.json { render action: 'show', status: :created, location: @examan }
      else
        format.html { render action: 'new' }
        format.json { render json: @examan.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @examan.etiquetas = get_etiquetas
    @examan.pregunta = get_preguntas
    @examan.preguntas_por_tema = get_cantidades

    respond_to do |format|
      if @examan.update(examan_params)
        format.html { redirect_to edit_examan_path(@examan), notice: 'Examan was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @examan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /examen/1
  # DELETE /examen/1.json
  def destroy
    @examan.destroy
    respond_to do |format|
      format.html { redirect_to examen_url }
      format.json { head :no_content }
    end
  end

  def update_clave
    examan = Examan.find(params[:examan])
    preguntas = examan.pregunta.ordenadas
    content = []
    index = 1
    preguntas.each do |pregunta|
      number = index.to_s
      number += '*' if pregunta.multiple  
      content << number
      index += 1
      content << "total: #{pregunta.opcions.count}"
      clave_pregunta = examan.clave(pregunta)
      minimo = params["minimo_#{pregunta.id}"].to_i
      clave_pregunta.minimo = minimo
      maximo = params["maximo_#{pregunta.id}"].to_i
      clave_pregunta.maximo = maximo
      opciones = ""
      pregunta.opcions.each do |opc|
        clave_opcion = clave_pregunta.clave(opc)
        clave_opcion.puntos_bien = params["opcion_#{clave_opcion.id}_bien"].to_f
        clave_opcion.puntos_mal = params["opcion_#{clave_opcion.id}_mal"].to_f
        opciones = opciones + clave_opcion.puntos_bien.to_s + ':' + 
                   clave_opcion.puntos_mal.to_s + ' '
        clave_opcion.save
      end
      content << opciones
      content << ''
      clave_pregunta.save
    end
    result = save_grader(examan, content)
    redirect_to clave_path(examan, :notice => result)
  end

  def save_grader(examan, content)
    directory = Rails.root.to_s + '/../generated/' + examan.directorio
    return 'Debe crear primero el examen.' if !File.exists?(directory) 
    directory += '/generated/last'
    grader = File.open(directory + '/grader.txt', 'r')
    version = grader.readline
    grader.close
    grader = File.open(directory + '/grader.txt', 'w')
    content.insert(0, version)
    content.insert(1, '')
    content = content.join("\n")
    grader.write(content)
    grader.close
    return 'La clave fue actualizada.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_examan
      @examan = Examan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def examan_params
      params.require(:examan).permit(:nombre, :etiquetas, :directorio, :cantidad, :asignatura_id, :variantes)
    end
end

webui/app/helpers/examen_helper.rb
module ExamenHelper
end

webui/app/views/examen/_form.html.erb
<%= form_for(@examan, :html => {:class => 'form-horizontal'}) do |f| %>
  <% if @examan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@examan.errors.count, "error") %> prohibited this examan from being saved:</h2>

      <ul>
      <% @examan.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field control-group">
    <%= f.label :nombre, :class => "control-label" %>
    <div class="controls">
      <%= f.text_field :nombre, :class => 'span4' %>
    </div>
  </div>

  <div class="field control-group">
    <%= f.label :directorio, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :directorio %>
    </div>
  </div>

  <div class="field control-group">
    <%= f.label 'Cantidad de Preguntas', :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :cantidad %>
    </div>
  </div>


  <div class="field control-group">
    <%= f.label :variantes, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :variantes %>
    </div>
  </div>

  <div class="field control-group">
    <%= f.label :etiquetas, :class => 'control-label' %>
    <div class="controls">
      <% for etiq in @asignatura.listado_de_etiquetas %>
        <%= check_box_tag "etiqueta_#{etiq}", 1, @examan.listado_de_etiquetas.include?(etiq) %> <%= etiq %> &nbsp; &nbsp;
      <% end %>
    </div>
  </div>

  <% unless @examan.new_record? %>
    <% if @examan.listado_de_etiquetas.count > 0 %>
      <div class="field control-group">
        <label class="control-label">Preguntas</label>
        <div class="controls">
          <div class="tabbable">
            <ul class="nav nav-tabs">
              <% first = true %>
              <% for etiqueta in @examan.listado_de_etiquetas %>
                <li class="<%= 'active' if first %>"><a href="#<%= buena_etiqueta(etiqueta) %>" data-toggle="tab"><%= etiqueta%></a></li>
                <% first = false%>
              <% end %>
            </ul>
            <div class="tab-content">
              <%
                first = true
                hash = {}
              %>
              <% for etiqueta in @examan.listado_de_etiquetas %>
                <div class="tab-pane <%= 'active'  if first %>" id="<%= buena_etiqueta(etiqueta) %>">
                  <% first = false %>
                  <% count = 0 %>
                  <% for pregunta in Preguntum.from_etiqueta(etiqueta)%>
                    <% #unless hash[pregunta.id] %>
                      <% count += 1%>
                      <label class="checkbox">
                        <%= check_box_tag "pregunta_#{pregunta.id}", 1, @examan.pregunta.include?(pregunta) %> <%= pregunta.titulo %>
                      </label>
                    <% end %>
                    <% hash[pregunta.id] = true %>
                  <% #end %>
                  <% if count == 0 %>
                    <i>NO HAY PREGUNTAS DE ESTA ETIQUETA</i> <br>
                  <% end %>
                  <%= number_field_tag "cantidad_#{etiqueta}", @examan.maximo(etiqueta), :class => :span1 %> Cantidad Mínima de preguntas a generar de esta etiqueta
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>

  <div class="form-actions">
    <%= f.hidden_field :asignatura_id %>
    <%= f.submit 'Crear Examen' %>
  </div>

<% end %>

webui/app/views/examen/clave.html.erb
<% content_for :menu do %>
  <%= link_to "Detalles de Examen", edit_examan_path(@examan), :class => 'btn btn-primary' %>
<% end %>

<h1> Definir clave </h1>

<%= form_tag update_clave_path(:examan => @examan) do  %>
<div class="accordion" id="accordion">
  <% number = 0 %>
  <% for pregunta in @examan.pregunta.ordenadas %>
    <% clave_pregunta = @examan.clave(pregunta) %>
    <% number += 1%>
    <div class="accordion-group">
      <div class="accordion-heading">
        <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapse_<%= pregunta.id %>"><%= pregunta.titulo_con_numero(number) %></a>
      </div>
      <div id="collapse_<%= pregunta.id%>" class="accordion-body collapse out">
        <div class="accordion-inner">
          Minimo: <%= number_field_tag "minimo_#{pregunta.id}", clave_pregunta.minimo || 0, :class => :span1 %> &nbsp; &nbsp; &nbsp;
          Maximo: <%= number_field_tag "maximo_#{pregunta.id}", clave_pregunta.maximo || 10, :class => :span1 %> <br>
          <% for opcion in pregunta.opcions %>
            <% clave_opcion = clave_pregunta.clave(opcion) %>
            <label class="checkbox">
              <div class="row">
                <div class="span7">
                  <%= check_box_tag "opcion_#{clave_opcion.id}_correcta", 1, clave_opcion.is_correct?, { 'disabled' => true } %>
                  <%= opcion.titulo %>
                </div>
                <div class="span5">
                  Marcada: <%= number_field_tag "opcion_#{clave_opcion.id}_bien", clave_opcion.puntos_bien.round(2), :style => "width: 50px; margin-left: 20px" %>
                  <br/>
                  No Marcada: <%= number_field_tag "opcion_#{clave_opcion.id}_mal", clave_opcion.puntos_mal.round(2), :style => "width: 50px" %>
                </div>
              </div>
            </label>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>
<%= submit_tag 'Guardar Cambios', :class => 'btn btn-primary' %>
<% end %>

webui/app/views/examen/edit.html.erb
<% content_for :menu do %>
  <%= link_to 'Detalles de Asignatura', @asignatura, :class => 'btn btn-primary' %>
  <%= link_to 'Definir Clave', clave_path(@examan), :class => 'btn btn-primary' %>
  <%= link_to 'Generar Master (latex)', latex_master_path(@examan), :class => 'btn btn-primary' %>
<% end %>

<h1>Editar Examen</h1>

<%= render 'form' %>

webui/app/views/examen/new.html.erb
<% content_for :menu do %>
  <%= link_to 'Detalles de Asignatura', @asignatura, :class => 'btn btn-primary' %>
<% end %>

<h1>Nuevo Examen</h1>

<%= render 'form' %>