webui/config/routes.rb
Examui::Application.routes.draw do

  resources :examen
  resources :listados
  resources :opcions
  resources :pregunta
  resources :asignaturas

  devise_for :users

  get 'nueva_pregunta/:id' => 'pregunta#nueva_pregunta', :as => :nueva_pregunta
  get 'nueva_opcion/:id' => 'opcions#nueva_opcion', :as => :nueva_opcion
  get 'nuevo_examen/:id' => 'examen#new', :as => :nuevo_examen
  get 'clave/:id' => 'examen#clave', :as => :clave
  get 'generate/latex/master/:id' => 'latex#latex_master', :as => :latex_master

  post 'update_clave' => 'examen#update_clave', :as => :update_clave

  root 'asignaturas#index'
end

webui/app/models/asignatura.rb
class Asignatura < ActiveRecord::Base
  has_many :pregunta
  has_one :listado
  has_many :examen
  after_save :ensure_listado

  def ensure_listado
    unless listado
      listado = Listado.new
      listado.asignatura_id = self.id
      listado.save
    end
  end

  def listado_de_etiquetas
    self.etiquetas.to_s.split(',').map {|e| e.strip }
  end

  def nombre_compuesto
    "#{nombre_largo} (#{nombre_corto})"
  end
end

webui/app/controllers/asignaturas_controller.rb
class AsignaturasController < ApplicationController
  before_action :set_asignatura, only: [:show, :edit, :update, :destroy]

  def index
    @asignaturas = Asignatura.all
  end

  def show
  end


  def new
    @asignatura = Asignatura.new
  end

  def edit
  end

  def create
    @asignatura = Asignatura.new(asignatura_params)

    respond_to do |format|
      if @asignatura.save
        format.html { redirect_to @asignatura, notice: 'Asignatura was successfully created.' }
        format.json { render action: 'show', status: :created, location: @asignatura }
      else
        format.html { render action: 'new' }
        format.json { render json: @asignatura.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @asignatura.update(asignatura_params)
        format.html { redirect_to @asignatura, notice: 'Asignatura was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @asignatura.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @asignatura.destroy
    respond_to do |format|
      format.html { redirect_to asignaturas_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_asignatura
      @asignatura = Asignatura.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def asignatura_params
      params.require(:asignatura).permit(:nombre_corto, :nombre_largo, :descripcion, :etiquetas)
    end
end

webui/app/helpers/asignaturas_helper.rb
module AsignaturasHelper
end

webui/app/views/asignaturas/_form.html.erb
<%= form_for(@asignatura, :html => {:class => 'form-horizontal'}) do |f| %>
  <% if @asignatura.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@asignatura.errors.count, 'error') %> prohibited this asignatura from being saved:</h2>

      <ul>
      <% @asignatura.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field control-group">
    <%= f.label :nombre_corto, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :nombre_corto %>
    </div>
  </div>

  <div class="field control-group">
    <%= f.label :nombre_largo, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :nombre_largo %>
    </div>
  </div>

  <div class="field control-group">
    <%= f.label :etiquetas, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :etiquetas %> (separadas por coma)
    </div>
  </div>

  <div class="field control-group">
    <%= f.label :descripción, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :descripcion %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit 'Crear Asignatura' %>
  </div>
<% end %>

webui/app/views/asignaturas/edit.html.erb
<% content_for :menu do %>
  <%= link_to 'Detalles Asignatura', @asignatura, :class => 'btn btn-primary' %>
  <%= link_to 'Listado de Asignaturas', asignaturas_path, :class => 'btn btn-primary' %>
  <%= link_to 'Agregar Pregunta', nueva_pregunta_path(@asignatura), :class => 'btn btn-primary' %>
  <%= link_to 'Crear Examen', '#', :class => 'btn btn-primary' %>
  <%= link_to 'Entrar Listado de Estudiantes', '#', :class => 'btn btn-primary' %>
<% end %>

<h1>Editar asignatura</h1>

<%= render 'form' %>

webui/app/views/asignaturas/index.html.erb
<% content_for :menu do %>
  <%= link_to 'Nueva Asignatura', new_asignatura_path, :class => 'btn btn-primary' %>
<% end %>

<h1>Asignaturas</h1>

<table class="table">
  <tr>
    <th>Nombre</th>
    <th>Etiquetas</th>
    <th>Preguntas</th>
    <th>Examenes</th>
    <th>Estudiantes</th>
    <th>Acciones</th>
  </tr>
<% @asignaturas.each do |asignatura| %>
  <tr>
    <td>
      <%= link_to asignatura.nombre_compuesto, asignatura, :class => 'link' %> <br>
      <%= asignatura.descripcion %>
    </td>
    <td> <%= etiquetas_de(asignatura) %> </td>
    <td> <%= asignatura.pregunta.count %> </td>
    <td> <%= asignatura.examen.count %> </td>
    <td> <%= asignatura.listado.estudiantes.split(',').length rescue 0 %> </td>
    <td>
      <%= link_to 'Detalles', asignatura, :class => 'btn btn-mini btn-info' %>
      <%= link_to 'Editar', edit_asignatura_path(asignatura), :class => 'btn btn-mini btn-success' %>
      <%= link_to 'Eliminar', asignatura, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-mini btn-danger'%>
    </td>
  </tr>
<% end %>
</table>

webui/app/views/asignaturas/new.html.erb
<% content_for :menu do %>
  <%= link_to 'Listado de Asignaturas', asignaturas_path, :class => 'btn btn-primary' %>
<% end %>

<h1>Nueva asignatura</h1>

<%= render 'form' %>

webui/app/views/asignaturas/show.html.erb
<% content_for :menu do %>
  <%= link_to 'Editar', edit_asignatura_path(@asignatura), :class => 'btn btn-primary' %>
  <%= link_to 'Agregar Pregunta', nueva_pregunta_path(@asignatura), :class => 'btn btn-primary' %>
  <%= link_to 'Crear Examen', nuevo_examen_path(@asignatura), :class => 'btn btn-primary' %>
  <%= link_to 'Estudiantes', edit_listado_path(@asignatura.listado), :class => 'btn btn-primary' %>
<% end %>

<% content_for :sidebar do %>
  <div class="well sidebar">
    <%= @asignatura.listado.estudiantes.html_safe rescue 0 %>
  </div>
<% end %>

<p id="notice"><%= notice %></p>

<h4>Detalles</h4>

<p>
  <strong>Nombre corto:</strong> <%= @asignatura.nombre_corto %> <br>
  <strong>Nombre largo:</strong> <%= @asignatura.nombre_largo %> <br>
  <strong>Descripcion:</strong> <%= @asignatura.descripcion %> <br>
</p>

<hr>

<div class="row">
  <div class="span6">
    <h4>Preguntas</h4>
    <table class="table table-striped">
      <% @asignatura.pregunta.each do |preguntum| %>
        <tr>
          <td>
            <b> <%= link_to preguntum.titulo, preguntum, :class => 'link' %> </b> <br>
            <%= etiquetas_de(preguntum) %>
          </td>
          <td>
            <%= link_to 'Eliminar', preguntum, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-mini btn-danger' %>
          </td>
        </tr>
      <% end %>
    </table>
  </div>
  <div class="span6">
    <h4>Examenes</h4>
    <table class="table table-striped">
      <% @asignatura.examen.each do |examan| %>
        <tr>
          <td>
            <b> <%= link_to examan.nombre, edit_examan_path(examan) %> </b> <br>
            Total de Preguntas: <span><%= examan.pregunta.count %></span>, &nbsp;
            Preguntas por Examen: <span><%= examan.cantidad %></span>, <br>
            Variantes a Generar: <span> <%= examan.variantes %> </span> &nbsp
            <%= etiquetas_de(examan) %>
          </td>
          <td>
            <%= link_to 'Eliminar', examan, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-mini btn-danger' %>
          </td>
        </tr>
      <% end %>
    </table>
  </div>
</div>